using MonsterLabZConfig.PrefabIniters;
using CreatureManager;
using ItemManager;
using LocationManager;


namespace MonsterLabZConfig.Loaders
{
    internal static class OtherLoader
    {
        public static void Load(BepInEx.Configuration.ConfigFile config)
        {
            ML_CustomProps();
            NPC_Items();

            Svartalf.init(config);
            MLNPC.init(config);
            Surtlings.init(config);
            Shadow.init(config);
        }

        private static void ML_CustomProps()
        {
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "CryptGateDoor");
            new Item("dybassets", "ML_MoltenOrb").Configurable = Configurability.Disabled;
            new Item("dybassets", "ML_Surtrstone_Fragment").Configurable = Configurability.Disabled;
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_Oak0_NoStatic");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_Birch0_NoStatic");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_Birch1_NoStatic");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_Birch_Sapling_NoStatic");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_Birch_log");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_Bush0_NoStatic");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_BushStub0_NoStatic");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_Barnacle");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_Runestone_Prop");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_SpiderCave_Exterior");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_RuinsHouse0");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_RuinsTower0");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_Grass1");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_Grass2");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_Fern_Large");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_Fern_Small");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_RedCrystal");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_RedCrystal_Small");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_RedCrystal_Mineable");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "fx_crystal_hit_ml");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "fx_redcrystal_destruction_ml");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_Incinerator_Weapons");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "ML_Torsten");
        }

        private static void NPC_Items()
        {

            new Item("dybassets", "attack_atgeir_360").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_atgeir_close").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_atgeir_long").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_axe_left180").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_axe_leftlong").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_axe_right180").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_axe_rightlong").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_axe_slash").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_baxe_180").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_baxe_360").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_baxe_long").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_bow").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_bow_stab").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_cast_enemy").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_cast_heal").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_cast_protect").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_club_left180").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_club_leftlong").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_club_right180").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_club_rightlong").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_club_slash").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_kick_atgeir").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_kick_baxe").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_kick_bow").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_kick_onehand").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_kick_shield").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_kick_sledge").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_kick_unarmed").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_knife_left180").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_knife_leftlong").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_knife_right180").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_knife_rightlong").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_knife_secondary").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_knife_slash").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_mace_left180").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_mace_right180").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_mace_slash").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_pickaxe_left180").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_pickaxe_right180").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_pickaxe_slash").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_shield").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_shield_block").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_sledge").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_sledge_360").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_sledge_jump").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_sledge_left180").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_sledge_right180").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_spear_jab").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_spear_throw").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_sword_dualcombo").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_sword_left180").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_sword_leftlong").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_sword_right180").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_sword_rightlong").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_sword_slash").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_taunt").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_unarmed_left").Configurable = Configurability.Disabled;
            new Item("dybassets", "attack_unarmed_right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_AtgeirBlackMetal").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_AtgeirBronze").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_AtgeirIron").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_AtgeirIronFire").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_AxeBlackMetal_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_AxeBlackMetal_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_AxeBronze_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_AxeBronze_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_AxeFlint_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_AxeFlint_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_AxeIron_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_AxeIron_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_AxeIronFire_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_AxeIronFire_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_AxeStone_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_AxeStone_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_BattleAxe").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Bow").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_BowDraugr").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_BowDraugrFang").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_BowFineWood").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_BowHuntsman").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Club_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Club_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_GreatSwordFire").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_GreatSwordFireBoss").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_KnifeBlackMetal_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_KnifeBlackMetal_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_KnifeBronze_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_KnifeBronze_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_KnifeChitin_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_KnifeChitin_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_KnifeFlint_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_KnifeFlint_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_MaceBronze_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_MaceBronze_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_MaceIron_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_MaceIron_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_MaceIronFire_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_MaceNeedle_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_MaceNeedle_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_MacePoison_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_MacePoison_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_MaceSilver_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_MaceSilver_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_PickaxeAntler").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_PickaxeBronze").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_PickaxeIron").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_PickaxeStone").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Scythe").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SledgeIron").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SledgeStagBreaker").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SledgeWood").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SpearBronze").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SpearChitin").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SpearElderBark").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SpearFlint").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SpearWolfFang").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Staff_Spider").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SwordBlackMetal_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SwordBlackMetal_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SwordBronze_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SwordBronze_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SwordIron_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SwordIron_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SwordIronFire_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SwordIronFire_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SwordSilver_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SwordSilver_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SwordSilverPoison_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_SwordSilverPoison_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Torch_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Torch_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_TorchMetal_Green_Left").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_TorchMetal_Green_Right").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_HelmetDrakeFire").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_ShieldBroken").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_ShieldSpiked").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_ArmorIronChest_Worn").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_ArmorIronLegs_Worn").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_ArmorBronzeLegs_Worn").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_HelmetIron_Worn0").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_HelmetBronze_Worn0").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_ShieldIron_Worn").Configurable = Configurability.Disabled;
            new Item("dybassets", "ShieldBanded_Worn").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_White_Hair0").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_White_Hair1").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_White_Hair2").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_White_Hair3").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_White_Hair4").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_White_Hair5").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_White_Hair6").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_White_Hair7").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_White_Hair8").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_White_Hair9").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_White_Hair10").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_White_Hair11").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_White_Hair12").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Black_Hair0").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Black_Hair1").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Black_Hair2").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Black_Hair3").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Black_Hair4").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Black_Hair5").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Black_Hair6").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Black_Hair7").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Black_Hair8").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Black_Hair9").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Black_Hair10").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Black_Hair11").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Black_Hair12").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Blonde_Hair0").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Blonde_Hair1").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Blonde_Hair2").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Blonde_Hair3").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Blonde_Hair4").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Blonde_Hair5").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Blonde_Hair6").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Blonde_Hair7").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Blonde_Hair8").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Blonde_Hair9").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Blonde_Hair10").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Blonde_Hair11").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Blonde_Hair12").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Brown_Hair0").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Brown_Hair1").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Brown_Hair2").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Brown_Hair3").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Brown_Hair4").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Brown_Hair5").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Brown_Hair6").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Brown_Hair7").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Brown_Hair8").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Brown_Hair9").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Brown_Hair10").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Brown_Hair11").Configurable = Configurability.Disabled;
            new Item("dybassets", "NPC_Brown_Hair12").Configurable = Configurability.Disabled;
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "Block_Shield");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "npc_fire_arrow_projectile");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "NPC_Arrow_Stab");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "npc_sledge_aoe_hit");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "npc_sledge_jump_aoe_hit");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "vfx_npc_sledge_hit");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "sfx_metal_armor_block");
            ItemManager.PrefabManager.RegisterPrefab("dybassets", "sfx_metal_shield_block");
        }
    }
}
